"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-hc--4q^*wzu7^(h9gl0v-ir1j$q993sdjddxljoix53j_2gd8o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites', #추가
    'apps.games',
    'apps.users',
    

    #allauth #추가
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    #provider #추가
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.kakao',
    'allauth.socialaccount.providers.naver',
]


SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'config.urls'
AUTH_USER_MODEL = 'users.User'
ACCOUNT_FORMS = {'signup': 'users.forms.CustomSignupForm'}
ACCOUNT_ADAPTER = 'apps.users.adapter.CustomAccountAdapter'
TEMPLATE_DIR = os.path.join(BASE_DIR, 'templates')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

ACCOUNT_SESSION_REMEMBER = False
# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = (
    #Needed to login by username in Django admin, regardless of 'allauth'
    'django.contrib.auth.backends.ModelBackend',

    # 'allauth' specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',

    
    
)


LOGIN_REDIRECT_URL = '/'







SOCIALACCOUNT_PROVIDERS ={
"kakao": {
"APP": {
"client_id": ("c41c9d1accde350cbb76e4e36c29fe16"),
"secret": "ff382e4f5f698f02d99418484b623a14",
"key": ""
},
# These are provider-specific settings that can only be
# listed here:
"SCOPE": [

],

"AUTH_PARAMS": {
"access_type": "online",
'prompt': 'select_account',
}},
######################################################

"naver": {
"APP": {
"client_id": ("JSv6sk6FvtglbqmUHUBT"),
"secret": ("cAjdyN7dnC"),
"key": ""
},
# These are provider-specific settings that can only be
# listed here:
"SCOPE": [

],

"AUTH_PARAMS": {
"access_type": "online",
'prompt': 'select_account',
}},
######################################################
"google": {
"APP": {
"client_id": ("765028604986-4bb5fu9s2147c3qsvqbq6g8af2jekc8j.apps.googleusercontent.com"),
"secret": ("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"),
"key": ""
},
"SCOPE": [
 "profile",
 "email",
],
"AUTH_PARAMS": {
"access_type": "online",
'prompt': 'select_account',
}}}
SOCIALACCOUNT_LOGIN_ON_GET = True

# SOCIALACCOUNT_PROVIDERS = {"naver": {
# "APP": {
# "client_id": os.getenv("JSv6sk6FvtglbqmUHUBT"),
# "secret": os.getenv("cAjdyN7dnC"),
# "key": ""
# },
# # These are provider-specific settings that can only be
# # listed here:
# "SCOPE": [
# "profile",
# "email",
# ],

# "AUTH_PARAMS": {
# "access_type": "online",
# }}}

# SOCIALACCOUNT_PROVIDERS = {
# "google": {
# "APP": {
# "client_id": os.getenv("765028604986-4bb5fu9s2147c3qsvqbq6g8af2jekc8j.apps.googleusercontent.com"),
# "secret": os.getenv("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"),
# "key": ""
# },
# # These are provider-specific settings that can only be
# # listed here:
# "SCOPE": [
# "profile",
# "email",
# ],

# "AUTH_PARAMS": {
# "access_type": "online",
# }}}