# Generated by Django 5.0.1 on 2024-01-19 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("a_choice", models.IntegerField(verbose_name="플레이어 A 선택 숫자")),
                (
                    "b_choice",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="플레이어 B 선택 숫자"
                    ),
                ),
                ("rule", models.IntegerField(verbose_name="랜덤 규칙")),
                (
                    "winner",
                    models.CharField(
                        blank=True, default=None, max_length=16, null=True
                    ),
                ),
                (
                    "player_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_a",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="플레이어 A",
                    ),
                ),
                (
                    "player_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_b",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="플레이어 B",
                    ),
                ),
            ],
        ),
    ]
