# Generated by Django 5.0.1 on 2024-01-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='b_choice',
            field=models.IntegerField(null=True, verbose_name='플레이어 B 선택 숫자'),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
