# Generated by Django 5.0.1 on 2024-01-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0003_alter_game_b_choice_alter_game_winner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="winner",
            field=models.CharField(default=None, max_length=16, null=True),
        ),
    ]
