# Generated by Django 5.0.1 on 2024-01-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0004_alter_game_winner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="b_choice",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="플레이어 B 선택 숫자"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="winner",
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
    ]
